### ISSUE TITLE
Application stops working without errors

### ISSUE THREAD

**Issue by stasizon** [JoeScho/get-ip-range#13]
In simple case with a specific ip range

```
const ipTools = require('get-ip-range')

console.log(ipTools.getIPRange('2400:ac40:0908:f:0:0:0:0-2400:ac40:0908:ffff:ffff:ffff:ffff:ffff'))
```

**Comment by JoeScho** [comment]
Hi @stasizon, could you provide some more information on how the application stops working? I've tried running this and it just hangs - probably because it's trying to calculate and return 1208649118453523531431936 IP addresses?

**Comment by JoeScho** [comment]
Actually this is a valid issue - looking into this

**Comment by JoeScho** [comment]
Hi @stasizon - I have now implemented a maximum default range of 10000 IPs in a range. This can be overridden using the `MAX_RANGE` environment variable. The reason for this issue was that it was trying to store every IP in memory, eventually causing an out-of-memory exception. Please upgrade to v4.0.0 to avoid this issue, thanks
